### ISSUE TITLE
make buttons_basys3_vivado failed due python assertion

### ISSUE THREAD

**Issue by YFWang97** [SymbiFlow/symbiflow-arch-defs#1256]
See following assertion when make vivado target for xc7/buttons_basys
Did not see from other tests. Suspect errors for wire "SW6END0"

```
Traceback (most recent call last):
  File "/home/yangfan/SymbiFlow/symbiflow-arch-defs/build/env/conda/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/yangfan/SymbiFlow/symbiflow-arch-defs/build/env/conda/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/yangfan/SymbiFlow/symbiflow-arch-defs/xc7/fasm2bels/__main__.py", line 4, in <module>
    main()
  File "/home/yangfan/SymbiFlow/symbiflow-arch-defs/xc7/fasm2bels/fasm2bels.py", line 296, in main
    top.make_routes(allow_orphan_sinks=args.allow_orphan_sinks)
  File "/home/yangfan/SymbiFlow/symbiflow-arch-defs/xc7/fasm2bels/verilog_modeling.py", line 1380, in make_routes
    net_map=self.net_map,
  File "/home/yangfan/SymbiFlow/symbiflow-arch-defs/xc7/fasm2bels/make_routes.py", line 700, in make_routes
    allow_orphan_sinks=allow_orphan_sinks
  File "/home/yangfan/SymbiFlow/symbiflow-arch-defs/xc7/fasm2bels/make_routes.py", line 579, in expand_sink
    allow_orphan_sinks=allow_orphan_sinks
  File "/home/yangfan/SymbiFlow/symbiflow-arch-defs/xc7/fasm2bels/make_routes.py", line 450, in expand_sink
    allow_orphan_sinks=allow_orphan_sinks
  File "/home/yangfan/SymbiFlow/symbiflow-arch-defs/xc7/fasm2bels/make_routes.py", line 579, in expand_sink
    allow_orphan_sinks=allow_orphan_sinks
  File "/home/yangfan/SymbiFlow/symbiflow-arch-defs/xc7/fasm2bels/make_routes.py", line 450, in expand_sink
    allow_orphan_sinks=allow_orphan_sinks
  File "/home/yangfan/SymbiFlow/symbiflow-arch-defs/xc7/fasm2bels/make_routes.py", line 450, in expand_sink
    allow_orphan_sinks=allow_orphan_sinks
  File "/home/yangfan/SymbiFlow/symbiflow-arch-defs/xc7/fasm2bels/make_routes.py", line 450, in expand_sink
    allow_orphan_sinks=allow_orphan_sinks
  [Previous line repeated 3 more times]
  File "/home/yangfan/SymbiFlow/symbiflow-arch-defs/xc7/fasm2bels/make_routes.py", line 610, in expand_sink
    assert False, (sink_node_pkey, tile_name, wire_name, sink_wire_pkey)
AssertionError: (386807, 'INT_L_X0Y129', 'SW6END0', 2329140)
xc7/tests/buttons/CMakeFiles/file_xc7_tests_buttons_buttons_basys3_artix7-xc7a50t-basys3-roi-virt-xc7a50t-basys3-test_top_bit.v.dir/build.make:62: recipe for target 'xc7/tests/buttons/buttons_basys3/artix7-xc7a50t-basys3-roi-virt-xc7a50t-basys3-test/top_bit.v' failed
make[3]: *** [xc7/tests/buttons/buttons_basys3/artix7-xc7a50t-basys3-roi-virt-xc7a50t-basys3-test/top_bit.v] Error 1
CMakeFiles/Makefile2:102285: recipe for target 'xc7/tests/buttons/CMakeFiles/file_xc7_tests_buttons_buttons_basys3_artix7-xc7a50t-basys3-roi-virt-xc7a50t-basys3-test_top_bit.v.dir/all' failed
make[2]: *** [xc7/tests/buttons/CMakeFiles/file_xc7_tests_buttons_buttons_basys3_artix7-xc7a50t-basys3-roi-virt-xc7a50t-basys3-test_top_bit.v.dir/all] Error 2
CMakeFiles/Makefile2:101526: recipe for target 'xc7/tests/buttons/CMakeFiles/buttons_basys3_vivado.dir/rule' failed
make[1]: *** [xc7/tests/buttons/CMakeFiles/buttons_basys3_vivado.dir/rule] Error 2
Makefile:30790: recipe for target 'buttons_basys3_vivado' failed
make: *** [buttons_basys3_vivado] Error 2
```

**Comment by litghost** [comment]
This issue doesn't appear to be happening any more.
