### ISSUE TITLE
Place constraints script ignores ROI

### ISSUE THREAD

**Issue by rw1nkler** [SymbiFlow/symbiflow-arch-defs#1517]
The `prjxray_create_place_constraints.py` script does not use the ROI parameters. It tries to place the PLL instances from the BUFGMUX test, outside the region of interest:

```Traceback (most recent call last):
  File "/home/build/rwinkler/symbiflow-arch-defs/xc/common/utils/prjxray_create_place_constraints.py", line 685, in <module>
    main()
  File "/home/build/rwinkler/symbiflow-arch-defs/xc/common/utils/prjxray_create_place_constraints.py", line 673, in main
    vpr_grid, loc_in_use, block_locs, blocks, grid_capacities):
  File "/home/build/rwinkler/symbiflow-arch-defs/xc/common/utils/prjxray_create_place_constraints.py", line 508, in place_clocks
    vpr_loc = vpr_locs[potential_loc]
KeyError: 'PLLE2_ADV_X1Y0'
```

The mentioned PLL is outside the region of interest.  The solution is to restrict the script to not use tiles outside the ROI.

**Comment by rw1nkler** [comment]
I was trying to lock all BUFG and PLL for this example, however, the script fails on this attempt:
```
Traceback (most recent call last):
  File "/home/build/rwinkler/symbiflow-arch-defs/xc/common/utils/prjxray_create_place_constraints.py", line 687, in <module>
    main()
  File "/home/build/rwinkler/symbiflow-arch-defs/xc/common/utils/prjxray_create_place_constraints.py", line 675, in main
    vpr_grid, loc_in_use, block_locs, blocks, grid_capacities):
  File "/home/build/rwinkler/symbiflow-arch-defs/xc/common/utils/prjxray_create_place_constraints.py", line 445, in place_clocks
    self.assign_cmts(vpr_grid, block_locs)
  File "/home/build/rwinkler/symbiflow-arch-defs/xc/common/utils/prjxray_create_place_constraints.py", line 437, in assign_cmts
    solutions = problem.getSolutions()
  File "/home/build/rwinkler/symbiflow-arch-defs/build/env/conda/lib/python3.7/site-packages/constraint/__init__.py", line 271, in getSolutions
    return self._solver.getSolutions(domains, constraints, vconstraints)
  File "/home/build/rwinkler/symbiflow-arch-defs/build/env/conda/lib/python3.7/site-packages/constraint/__init__.py", line 567, in getSolutions
    return list(self.getSolutionIter(domains, constraints, vconstraints))
  File "/home/build/rwinkler/symbiflow-arch-defs/build/env/conda/lib/python3.7/site-packages/constraint/__init__.py", line 544, in getSolutionIter
    if not constraint(variables, domains, assignments, pushdomains):
  File "/home/build/rwinkler/symbiflow-arch-defs/build/env/conda/lib/python3.7/site-packages/constraint/__init__.py", line 991, in __call__
    self.forwardCheck(variables, domains, assignments)
  File "/home/build/rwinkler/symbiflow-arch-defs/build/env/conda/lib/python3.7/site-packages/constraint/__init__.py", line 935, in forwardCheck
    if not self(variables, domains, assignments):
  File "/home/build/rwinkler/symbiflow-arch-defs/build/env/conda/lib/python3.7/site-packages/constraint/__init__.py", line 993, in __call__
    return self._func(*parms)
  File "/home/build/rwinkler/symbiflow-arch-defs/xc/common/utils/prjxray_create_place_constraints.py", line 427, in <lambda>
    source] == sink_bufg,
TypeError: unhashable type: 'dict'
```
