### ISSUE TITLE
error when "make env" 

### ISSUE THREAD

**Issue by yongshiwo** [SymbiFlow/symbiflow-arch-defs#1802]
OS_TYPE=Linux CPU_TYPE=x86_64
'name: symbiflow_arch_def_base' 'symbiflow_arch_def_base'
chmod a+x /mnt/sas1/home/zyzhang/workspace/symbiflow-arch-defs/env/downloads/Miniconda3-latest-Linux-x86_64.sh
/mnt/sas1/home/zyzhang/workspace/symbiflow-arch-defs/env/downloads/Miniconda3-latest-Linux-x86_64.sh -p /mnt/sas1/home/zyzhang/workspace/symbiflow-arch-defs/env/conda -b -f
PREFIX=/mnt/sas1/home/zyzhang/workspace/symbiflow-arch-defs/env/conda
Unpacking payload ...
Traceback (most recent call last):
  File "entry_point.py", line 59, in <module>
  File "concurrent/futures/process.py", line 555, in __init__
  File "concurrent/futures/process.py", line 165, in __init__
  File "multiprocessing/queues.py", line 42, in __init__
  File "multiprocessing/context.py", line 68, in Lock
  File "multiprocessing/synchronize.py", line 162, in __init__
  File "multiprocessing/synchronize.py", line 57, in __init__
PermissionError: [Errno 13] Permission denied
[22015] Failed to execute script entry_point
third_party/make-env/conda.mk:118: recipe for target '/mnt/sas1/home/zyzhang/workspace/symbiflow-arch-defs/env/conda/bin/python' failed
make: *** [/mnt/sas1/home/zyzhang/workspace/symbiflow-arch-defs/env/conda/bin/python] Error 1

**Comment by umarcor** [comment]
@yongshiwo, is this still relevant? Did you try with a more recent version?
