### ISSUE TITLE
RapidWright fails with "No enum constant com.xilinx.rapidwright.device.FamilyType.VERSAL"

### ISSUE THREAD

**Issue by HackerFoo** [SymbiFlow/symbiflow-arch-defs#1915]
Xilinx vendor tool test fails on master (e.g. https://github.com/SymbiFlow/symbiflow-arch-defs/pull/1912), coinciding with this release: https://github.com/Xilinx/RapidWright/releases/tag/v2020.2.0-beta

```
FAILED: cd /tmpfs/src/github/symbiflow-arch-defs-presubmit-xc7-vendor/build/tests/9-soc/picosoc && /tmpfs/src/github/symbiflow-arch-defs-presubmit-xc7-vendor/env/conda/envs/symbiflow_arch_def_base/bin/cmake -E env JAVA=/usr/bin/java RAPIDWRIGHT_PATH=/tmpfs/src/github/symbiflow-arch-defs-presubmit-xc7-vendor/env/RapidWright /tmpfs/src/github/symbiflow-arch-defs-presubmit-xc7-vendor/env/RapidWright/scripts/invoke_rapidwright.sh com.xilinx.rapidwright.interchange.PhysicalNetlistToDcp /tmpfs/src/github/symbiflow-arch-defs-presubmit-xc7-vendor/build/tests/9-soc/picosoc/picosoc_basys3_full_50/artix7-xc7a50t-virt-xc7a50t-test/basys3_demo_bit.v.netlist /tmpfs/src/github/symbiflow-arch-defs-presubmit-xc7-vendor/build/tests/9-soc/picosoc/picosoc_basys3_full_50/artix7-xc7a50t-virt-xc7a50t-test/basys3_demo_bit.v.phys /tmpfs/src/github/symbiflow-arch-defs-presubmit-xc7-vendor/build/tests/9-soc/picosoc/picosoc_basys3_full_50/artix7-xc7a50t-virt-xc7a50t-test/basys3_demo_bit.v.inter.xdc picosoc_basys3_full_50/artix7-xc7a50t-virt-xc7a50t-test/interchange/picosoc_basys3_full_50_vivado_interchange.dcp
Exception in thread "main" java.lang.IllegalArgumentException: No enum constant com.xilinx.rapidwright.device.FamilyType.VERSAL
	at java.lang.Enum.valueOf(Enum.java:238)
	at com.xilinx.rapidwright.device.FamilyType.valueOf(FamilyType.java:34)
	at com.xilinx.rapidwright.design.i.a(Unknown Source)
	at com.xilinx.rapidwright.design.i.<init>(Unknown Source)
	at com.xilinx.rapidwright.design.i.a(Unknown Source)
	at com.xilinx.rapidwright.design.Design.getUnisimCell(Unknown Source)
	at com.xilinx.rapidwright.interchange.LogNetlistReader.readEDIFCell(LogNetlistReader.java:185)
	at com.xilinx.rapidwright.interchange.LogNetlistReader.getLogNetlist(LogNetlistReader.java:300)
	at com.xilinx.rapidwright.interchange.LogNetlistReader.readLogNetlist(LogNetlistReader.java:277)
	at com.xilinx.rapidwright.interchange.PhysicalNetlistToDcp.main(PhysicalNetlistToDcp.java:33)
```

Related: https://github.com/SymbiFlow/symbiflow-arch-defs/pull/1772

**Comment by litghost** [comment]
Immediate issue resolved: https://github.com/Xilinx/RapidWright/pull/114#issuecomment-754822222
