### ISSUE TITLE
make env fails on arch

### ISSUE THREAD

**Issue by mgerlach-phys** [SymbiFlow/symbiflow-arch-defs#1999]
Hello,

it seems that pip crashes while installing `rapidyaml` due to the [common issue](https://stackoverflow.com/questions/65059605/error-could-not-build-wheels-for-pynacl-which-use-pep-517-and-cannot-be-install?answertab=active#tab-top) with PEP 517 in venv.

Backtrace:

```
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
Installing pip dependencies: / Ran pip subprocess with arguments:
- ['/home/charm/FPGA/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/python', '-m', 'pip', 'install', '-U', '-r', '/home/charm/FPGA/symbiflow-arch-defs/condaenv.onzcg5y2.requirements.txt']
Pip subprocess output:
Collecting rr-graph
  Cloning https://github.com/SymbiFlow/symbiflow-rr-graph.git to /tmp/pip-install-n23692y_/rr-graph_ec17cac8926f467492ef1e3affa1b3fe
Collecting rapidyaml
  Cloning https://github.com/litghost/rapidyaml.git (to revision fixup_python_packaging) to /tmp/pip-install-n23692y_/rapidyaml_76260b282025438ea3e1f96d2a36d871
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
    Preparing wheel metadata: started
    Preparing wheel metadata: finished with status 'done'
Collecting python-fpga-interchange
  Cloning https://github.com/SymbiFlow/python-fpga-interchange.git to /tmp/pip-install-n23692y_/python-fpga-interchange_2c9f42d640f84435b68a47600096b686
Obtaining file:///home/charm/FPGA/symbiflow-arch-defs/third_party/prjxray (from -r file:requirements.txt (line 26))
Obtaining file:///home/charm/FPGA/symbiflow-arch-defs/third_party/fasm (from -r file:requirements.txt (line 27))
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
    Preparing wheel metadata: started
    Preparing wheel metadata: finished with status 'done'
Obtaining file:///home/charm/FPGA/symbiflow-arch-defs/third_party/xc-fasm (from -r file:requirements.txt (line 28))
Obtaining file:///home/charm/FPGA/symbiflow-arch-defs/third_party/python-sdf-timing (from -r file:requirements.txt (line 29))
Obtaining file:///home/charm/FPGA/symbiflow-arch-defs/third_party/python-symbiflow-v2x (from -r file:requirements.txt (line 30))
Obtaining file:///home/charm/FPGA/symbiflow-arch-defs/third_party/vtr-xml-utils (from -r file:requirements.txt (line 31))
Obtaining file:///home/charm/FPGA/symbiflow-arch-defs/third_party/symbiflow-xc-fasm2bels (from -r file:requirements.txt (line 32))
Obtaining file:///home/charm/FPGA/symbiflow-arch-defs/third_party/litex (from -r file:requirements.txt (line 33))
Obtaining file:///home/charm/FPGA/symbiflow-arch-defs/third_party/litex-boards (from -r file:requirements.txt (line 34))
Obtaining file:///home/charm/FPGA/symbiflow-arch-defs/third_party/litedram (from -r file:requirements.txt (line 35))
Obtaining file:///home/charm/FPGA/symbiflow-arch-defs/third_party/liteeth (from -r file:requirements.txt (line 36))
Obtaining file:///home/charm/FPGA/symbiflow-arch-defs/third_party/liteiclink (from -r file:requirements.txt (line 37))
Obtaining file:///home/charm/FPGA/symbiflow-arch-defs/third_party/migen (from -r file:requirements.txt (line 38))
Processing ./third_party/pythondata-cpu-vexriscv
Processing ./third_party/pythondata-software-compiler_rt
Collecting git+https://github.com/lowRISC/edalize.git@ot (from -r file:requirements.txt (line 42))
  Cloning https://github.com/lowRISC/edalize.git (to revision ot) to /tmp/pip-req-build-txkupf73
Collecting git+https://github.com/lowRISC/fusesoc.git@ot (from -r file:requirements.txt (line 43))
  Cloning https://github.com/lowRISC/fusesoc.git (to revision ot) to /tmp/pip-req-build-3y5f6e8r
Collecting hilbertcurve==1.0.5
  Downloading hilbertcurve-1.0.5.tar.gz (6.7 kB)
Collecting pycapnp==1.0.0b1
  Downloading pycapnp-1.0.0b1-cp37-cp37m-manylinux2010_x86_64.whl (4.0 MB)
Collecting yapf==0.26.0
  Downloading yapf-0.26.0-py2.py3-none-any.whl (176 kB)
Collecting ipyxact>=0.2.3
  Downloading ipyxact-0.2.4.tar.gz (19 kB)
Collecting Jinja2!=2.11.0,!=2.11.1,>=2.8
  Downloading Jinja2-2.11.3-py2.py3-none-any.whl (125 kB)
Collecting MarkupSafe>=0.23
  Downloading MarkupSafe-1.1.1-cp37-cp37m-manylinux2010_x86_64.whl (33 kB)
Collecting simplesat>=0.8.0
  Downloading simplesat-0.8.2-py2.py3-none-any.whl (246 kB)
Collecting attrs>=17.4.0
  Using cached attrs-20.3.0-py2.py3-none-any.whl (49 kB)
Collecting okonomiyaki>=0.16.6
  Downloading okonomiyaki-1.2.0-py2.py3-none-any.whl (523 kB)
Collecting jsonschema>=2.5.1
  Downloading jsonschema-3.2.0-py2.py3-none-any.whl (56 kB)
Requirement already satisfied: setuptools in ./env/conda/envs/symbiflow_arch_def_base/lib/python3.7/site-packages (from jsonschema>=2.5.1->okonomiyaki>=0.16.6->simplesat>=0.8.0->fusesoc==1.11.dev57+g1fb8c93->-r file:requirements.txt (line 43)) (52.0.0.post20210125)
Requirement already satisfied: importlib-metadata in ./env/conda/envs/symbiflow_arch_def_base/lib/python3.7/site-packages (from jsonschema>=2.5.1->okonomiyaki>=0.16.6->simplesat>=0.8.0->fusesoc==1.11.dev57+g1fb8c93->-r file:requirements.txt (line 43)) (2.0.0)
Collecting pyrsistent>=0.14.0
  Downloading pyrsistent-0.17.3.tar.gz (106 kB)
Collecting six>=1.10.0
  Using cached six-1.15.0-py2.py3-none-any.whl (10 kB)
Collecting zipfile2>=0.0.12
  Downloading zipfile2-0.0.12-py2.py3-none-any.whl (44 kB)
Collecting cairosvg
  Downloading CairoSVG-2.5.1-py3-none-any.whl (45 kB)
Collecting gitpython
  Downloading GitPython-3.1.12-py3-none-any.whl (159 kB)
Collecting gitdb<5,>=4.0.1
  Downloading gitdb-4.0.5-py3-none-any.whl (63 kB)
Collecting smmap<4,>=3.0.1
  Downloading smmap-3.0.5-py2.py3-none-any.whl (25 kB)
Collecting intervaltree
  Downloading intervaltree-3.1.0.tar.gz (32 kB)
Collecting sortedcontainers<3.0,>=2.0
  Downloading sortedcontainers-2.3.0-py2.py3-none-any.whl (29 kB)
Collecting mako
  Downloading Mako-1.1.4.tar.gz (479 kB)
Collecting matplotlib
  Downloading matplotlib-3.3.4-cp37-cp37m-manylinux1_x86_64.whl (11.5 MB)
Collecting numpy
  Downloading numpy-1.20.0-cp37-cp37m-manylinux2010_x86_64.whl (15.3 MB)
Collecting cycler>=0.10
  Downloading cycler-0.10.0-py2.py3-none-any.whl (6.5 kB)
Collecting kiwisolver>=1.0.1
  Downloading kiwisolver-1.3.1-cp37-cp37m-manylinux1_x86_64.whl (1.1 MB)
Collecting pillow
  Downloading Pillow-8.1.0-cp37-cp37m-manylinux1_x86_64.whl (2.2 MB)
Collecting pyparsing
  Using cached pyparsing-2.4.7-py2.py3-none-any.whl (67 kB)
Collecting python-dateutil>=2.1
  Downloading python_dateutil-2.8.1-py2.py3-none-any.whl (227 kB)
Collecting pdfminer.six
  Downloading pdfminer.six-20201018-py3-none-any.whl (5.6 MB)
Collecting ply
  Downloading ply-3.11-py2.py3-none-any.whl (49 kB)
Collecting progressbar2
  Downloading progressbar2-3.53.1-py2.py3-none-any.whl (25 kB)
Collecting python-utils>=2.3.0
  Downloading python_utils-2.5.5-py2.py3-none-any.whl (12 kB)
Collecting pyjson5
  Downloading pyjson5-1.4.8-cp37-cp37m-manylinux2014_x86_64.whl (259 kB)
Collecting pytest
  Downloading pytest-6.2.2-py3-none-any.whl (280 kB)
Requirement already satisfied: zipp>=0.5 in ./env/conda/envs/symbiflow_arch_def_base/lib/python3.7/site-packages (from importlib-metadata->jsonschema>=2.5.1->okonomiyaki>=0.16.6->simplesat>=0.8.0->fusesoc==1.11.dev57+g1fb8c93->-r file:requirements.txt (line 43)) (3.4.0)
Collecting pluggy<1.0.0a1,>=0.12
  Using cached pluggy-0.13.1-py2.py3-none-any.whl (18 kB)
Collecting py>=1.8.2
  Using cached py-1.10.0-py2.py3-none-any.whl (97 kB)
Collecting python-constraint
  Downloading python-constraint-1.4.0.tar.bz2 (18 kB)
Collecting pyyaml
  Downloading PyYAML-5.4.1-cp37-cp37m-manylinux1_x86_64.whl (636 kB)
Collecting scipy
  Downloading scipy-1.6.0-cp37-cp37m-manylinux1_x86_64.whl (27.4 MB)
Collecting simplejson
  Downloading simplejson-3.17.2-cp37-cp37m-manylinux2010_x86_64.whl (128 kB)
Collecting svgwrite
  Downloading svgwrite-1.4.1-py3-none-any.whl (66 kB)
Collecting textx
  Downloading textX-2.3.0-py2.py3-none-any.whl (72 kB)
Collecting Arpeggio>=1.9.0
  Downloading Arpeggio-1.10.1-py2.py3-none-any.whl (54 kB)
Collecting tinyfpgab
  Downloading tinyfpgab-1.1.0.tar.gz (4.6 kB)
Collecting tinyprog
  Downloading tinyprog-1.0.21-py3-none-any.whl (10 kB)
Collecting intelhex<3,>=2.2.1
  Downloading intelhex-2.3.0-py2.py3-none-any.whl (50 kB)
Collecting jsonmerge<2,>=1.4.0
  Downloading jsonmerge-1.8.0.tar.gz (26 kB)
Collecting pyserial
  Downloading pyserial-3.5-py2.py3-none-any.whl (90 kB)
Collecting tqdm<5,>=4.19.5
  Downloading tqdm-4.56.0-py2.py3-none-any.whl (72 kB)
Collecting cairocffi
  Downloading cairocffi-1.2.0.tar.gz (70 kB)
Collecting cffi>=1.1.0
  Using cached cffi-1.14.4-cp37-cp37m-manylinux1_x86_64.whl (402 kB)
Collecting chardet
  Downloading chardet-4.0.0-py2.py3-none-any.whl (178 kB)
Collecting colorama
  Downloading colorama-0.4.4-py2.py3-none-any.whl (16 kB)
Collecting cryptography
  Downloading cryptography-3.3.1-cp36-abi3-manylinux2010_x86_64.whl (2.6 MB)
Collecting cssselect2
  Downloading cssselect2-0.4.1-py3-none-any.whl (13 kB)
Collecting defusedxml
  Downloading defusedxml-0.6.0-py2.py3-none-any.whl (23 kB)
Collecting iniconfig
  Using cached iniconfig-1.1.1-py2.py3-none-any.whl (5.0 kB)
Collecting lxml
  Downloading lxml-4.6.2-cp37-cp37m-manylinux1_x86_64.whl (5.5 MB)
Collecting packaging
  Downloading packaging-20.9-py2.py3-none-any.whl (40 kB)
Collecting parameterized
  Downloading parameterized-0.8.1-py2.py3-none-any.whl (26 kB)
Collecting pycparser
  Using cached pycparser-2.20-py2.py3-none-any.whl (112 kB)
Collecting pyjson
  Downloading pyjson-1.3.0-py3-none-any.whl (4.8 kB)
Collecting pyusb
  Downloading pyusb-1.1.1-py3-none-any.whl (58 kB)
Collecting requests
  Downloading requests-2.25.1-py2.py3-none-any.whl (61 kB)
Requirement already satisfied: certifi>=2017.4.17 in ./env/conda/envs/symbiflow_arch_def_base/lib/python3.7/site-packages (from requests->litex==0.0.0->-r file:requirements.txt (line 33)) (2020.12.5)
Collecting idna<3,>=2.5
  Downloading idna-2.10-py2.py3-none-any.whl (58 kB)
Collecting urllib3<1.27,>=1.21.1
  Downloading urllib3-1.26.3-py2.py3-none-any.whl (137 kB)
Collecting tinycss2
  Downloading tinycss2-1.1.0-py3-none-any.whl (21 kB)
Collecting webencodings
  Downloading webencodings-0.5.1-py2.py3-none-any.whl (11 kB)
Collecting toml
  Using cached toml-0.10.2-py2.py3-none-any.whl (16 kB)
Building wheels for collected packages: edalize, fusesoc, python-fpga-interchange, pythondata-cpu-vexriscv, pythondata-software-compiler-rt, rapidyaml, rr-graph, hilbertcurve, ipyxact, pyrsistent, intervaltree, mako, python-constraint, tinyfpgab, jsonmerge, cairocffi
  Building wheel for edalize (setup.py): started
  Building wheel for edalize (setup.py): finished with status 'done'
  Created wheel for edalize: filename=edalize-0.2.2-py3-none-any.whl size=62604 sha256=86d454ce996b39ad4c30e52afef6734c65c864a3dabce4f40470f7fe4231dad8
  Stored in directory: /tmp/pip-ephem-wheel-cache-tffh_3fu/wheels/7f/04/29/5d606dc370acbacc8a1ee3005da53e5ef1ff2704d97260dcae
  Building wheel for fusesoc (setup.py): started
  Building wheel for fusesoc (setup.py): finished with status 'done'
  Created wheel for fusesoc: filename=fusesoc-1.11.dev57+g1fb8c93-py3-none-any.whl size=62636 sha256=440902723ec39742e7b30688446b58aa6438004cf2b7853f260d6087b5de1f75
  Stored in directory: /tmp/pip-ephem-wheel-cache-tffh_3fu/wheels/67/81/11/e24f2ee1b0aa7790249073e32c0810dc6d263cf8aed3e3fe08
  Building wheel for python-fpga-interchange (setup.py): started
  Building wheel for python-fpga-interchange (setup.py): finished with status 'done'
  Created wheel for python-fpga-interchange: filename=python_fpga_interchange-0.0.1-py3-none-any.whl size=44555 sha256=e53c72d308e069816a3a6237da51e3149d1a0949c9ea706dbcd94fe0e6acf257
  Stored in directory: /tmp/pip-ephem-wheel-cache-tffh_3fu/wheels/93/31/f8/f8f96e60cdd4dececcaaa62d40b7ee8b36488c5d6e3dc351a0
  Building wheel for pythondata-cpu-vexriscv (setup.py): started
  Building wheel for pythondata-cpu-vexriscv (setup.py): finished with status 'done'
  Created wheel for pythondata-cpu-vexriscv: filename=pythondata_cpu_vexriscv-1.0.1.post325-py3-none-any.whl size=19617070 sha256=d444c162dd7cb584197603d848c37694e162185e2192ad9d08e891c185e2f32f
  Stored in directory: /home/charm/.cache/pip/wheels/0d/0c/f4/39394fe23d579be6fe70ec6a9091224d888130ae6f5a9df9c7
  Building wheel for pythondata-software-compiler-rt (setup.py): started
  Building wheel for pythondata-software-compiler-rt (setup.py): finished with status 'done'
  Created wheel for pythondata-software-compiler-rt: filename=pythondata_software_compiler_rt-0.0.post6200-py3-none-any.whl size=3220702 sha256=b9c20c190a1c927f5e8026171c6d013e6e50f6d9655f9a4066a657b814beb1c9
  Stored in directory: /home/charm/.cache/pip/wheels/b5/e4/44/63f1682e1a2e4581329c3291b1f7f012be303ef5498aa92efd
  Building wheel for rapidyaml (PEP 517): started
  Building wheel for rapidyaml (PEP 517): finished with status 'error'
  Building wheel for rr-graph (setup.py): started
  Building wheel for rr-graph (setup.py): finished with status 'done'
  Created wheel for rr-graph: filename=rr_graph-0.0.1-py3-none-any.whl size=69119 sha256=9f70b1dead8b2ff7f3e72cd5efba12c1cc764e44de37104c00691ce4c5c2f12d
  Stored in directory: /tmp/pip-ephem-wheel-cache-tffh_3fu/wheels/ac/8b/c0/dc4abae831fc27fb16dc9ca87dd4debafbf6c34526d5ff0a07
  Building wheel for hilbertcurve (setup.py): started
  Building wheel for hilbertcurve (setup.py): finished with status 'done'
  Created wheel for hilbertcurve: filename=hilbertcurve-1.0.5-py3-none-any.whl size=6510 sha256=fd0e1655264cb7e38fa8ac7b85120806754b0243f5010407b1cb095c2f6c63a3
  Stored in directory: /home/charm/.cache/pip/wheels/4c/e5/b7/c9bb012d3d54c3038997be3b60f935a8055bbd2c5cf93d7649
  Building wheel for ipyxact (setup.py): started
  Building wheel for ipyxact (setup.py): finished with status 'done'
  Created wheel for ipyxact: filename=ipyxact-0.2.4-py3-none-any.whl size=5971 sha256=1ccc9c673a21cf334aa7d9e3c1f2228ca32eb6f1b8adbb939768e2595bbb3e81
  Stored in directory: /home/charm/.cache/pip/wheels/f1/4b/18/ef2f6731ecd0898b07d40a5179c7307cbd435224b9f1cfbd3d
  Building wheel for pyrsistent (setup.py): started
  Building wheel for pyrsistent (setup.py): finished with status 'done'
  Created wheel for pyrsistent: filename=pyrsistent-0.17.3-cp37-cp37m-linux_x86_64.whl size=116567 sha256=2e6186d401690b98bc35cce7fc641329cf9c42d7b27b8d8e1846eb3cea05ee12
  Stored in directory: /home/charm/.cache/pip/wheels/a5/52/bf/71258a1d7b3c8cbe1ee53f9314c6f65f20385481eaee573cc5
  Building wheel for intervaltree (setup.py): started
  Building wheel for intervaltree (setup.py): finished with status 'done'
  Created wheel for intervaltree: filename=intervaltree-3.1.0-py2.py3-none-any.whl size=26102 sha256=c65ec0e13fbbe9561689caebe0e817aeb0661fe7c7206ef72773514e79dea744
  Stored in directory: /home/charm/.cache/pip/wheels/16/85/bd/1001cbb46dcfb71c2001cd7401c6fb250392f22a81ce3722f7
  Building wheel for mako (setup.py): started
  Building wheel for mako (setup.py): finished with status 'done'
  Created wheel for mako: filename=Mako-1.1.4-py2.py3-none-any.whl size=75675 sha256=ed2cff7b08f454e8eb7bf663055ee6865390ad28bbf1eae2feaa137fa2ee032d
  Stored in directory: /home/charm/.cache/pip/wheels/2a/60/32/02a16820f96c067f6161ef35c21559f8db52c4158d6602b438
  Building wheel for python-constraint (setup.py): started
  Building wheel for python-constraint (setup.py): finished with status 'done'
  Created wheel for python-constraint: filename=python_constraint-1.4.0-py2.py3-none-any.whl size=24079 sha256=e196547cde24ca0580d724958989f731ff32b8a811a6df83ed735b0555295dda
  Stored in directory: /home/charm/.cache/pip/wheels/07/27/db/1222c80eb1e431f3d2199c12569cb1cac60f562a451fe30479
  Building wheel for tinyfpgab (setup.py): started
  Building wheel for tinyfpgab (setup.py): finished with status 'done'
  Created wheel for tinyfpgab: filename=tinyfpgab-1.1.0-py3-none-any.whl size=5452 sha256=3b2d7a37ce29d3ec4207117ededa01722b264ae2d7ed60b33b57398441a36dba
  Stored in directory: /home/charm/.cache/pip/wheels/22/96/aa/7f1aa060a1a6f3ff28c69be210df72260d57ac072ff19213f5
  Building wheel for jsonmerge (setup.py): started
  Building wheel for jsonmerge (setup.py): finished with status 'done'
  Created wheel for jsonmerge: filename=jsonmerge-1.8.0-py3-none-any.whl size=17995 sha256=483bb1c08e051544bcfea9d58d2c3afc45c3d971fff16f0d375cb80221db5d8f
  Stored in directory: /home/charm/.cache/pip/wheels/2f/c8/79/83ddc70e0b20f2df3bbac658c2c5d665b76cedd02e67bd61dc
  Building wheel for cairocffi (setup.py): started
  Building wheel for cairocffi (setup.py): finished with status 'done'
  Created wheel for cairocffi: filename=cairocffi-1.2.0-py3-none-any.whl size=89545 sha256=d8e10474d08a1858c1d8500f292586033204f467481a89cdcaeb040c9ee164c9
  Stored in directory: /home/charm/.cache/pip/wheels/e2/ca/86/9db2824f203afe4bdf5aa6ead017f352fcc90e92f095b78871
Successfully built edalize fusesoc python-fpga-interchange pythondata-cpu-vexriscv pythondata-software-compiler-rt rr-graph hilbertcurve ipyxact pyrsistent intervaltree mako python-constraint tinyfpgab jsonmerge cairocffi
Failed to build rapidyaml

Pip subprocess error:
  ERROR: Command errored out with exit status 1:
   command: /home/charm/FPGA/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/python /home/charm/FPGA/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py build_wheel /tmp/tmpx_iwy_q9
       cwd: /tmp/pip-install-n23692y_/rapidyaml_76260b282025438ea3e1f96d2a36d871/api/python
  Complete output (86 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.7
  creating build/lib.linux-x86_64-3.7/ryml
  copying ryml/__init__.py -> build/lib.linux-x86_64-3.7/ryml
  running build_ext
  -- The CXX compiler identification is GNU 10.2.0
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Check for working CXX compiler: /usr/bin/c++ - skipped
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  -- ryml: using C++ standard: C++11
  -- ryml: setting C++ standard: 11
  -- ryml: setting C++ standard required: ON
  -- ryml: importing subproject c4core (SUBDIRECTORY)... /tmp/pip-install-n23692y_/rapidyaml_76260b282025438ea3e1f96d2a36d871/ext/c4core
  -- c4core: using C++ standard: C++11
  -- ryml: -----> target ryml PUBLIC incorporating lib c4core
  -- ryml: packing the project
  -- ryml: enabling API
  CMake Error at /home/charm/FPGA/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/share/cmake-3.19/Modules/FindPackageHandleStandardArgs.cmake:218 (message):
    Could NOT find SWIG (missing: SWIG_EXECUTABLE SWIG_DIR)
  Call Stack (most recent call first):
    /home/charm/FPGA/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/share/cmake-3.19/Modules/FindPackageHandleStandardArgs.cmake:582 (_FPHSA_FAILURE_MESSAGE)
    /home/charm/FPGA/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/share/cmake-3.19/Modules/FindSWIG.cmake:138 (find_package_handle_standard_args)
    api/CMakeLists.txt:11 (find_package)
  
  
  -- Configuring incomplete, errors occurred!
  See also "/tmp/pip-install-n23692y_/rapidyaml_76260b282025438ea3e1f96d2a36d871/api/python/build/temp.linux-x86_64-3.7_ryml.ryml/CMakeFiles/CMakeOutput.log".
  
  ==> Configuring:
  $ cmake -S /tmp/pip-install-n23692y_/rapidyaml_76260b282025438ea3e1f96d2a36d871/api/python/../.. -B /tmp/pip-install-n23692y_/rapidyaml_76260b282025438ea3e1f96d2a36d871/api/python/build/temp.linux-x86_64-3.7_ryml.ryml -GNinja -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX:PATH=/tmp/pip-install-n23692y_/rapidyaml_76260b282025438ea3e1f96d2a36d871/api/python/build/lib.linux-x86_64-3.7/ryml -DRYML_BUILD_API:BOOL=ON
  
  ==> Building:
  $ cmake --build /tmp/pip-install-n23692y_/rapidyaml_76260b282025438ea3e1f96d2a36d871/api/python/build/temp.linux-x86_64-3.7_ryml.ryml --config Release
  
  ==> Installing:
  $ cmake --build /tmp/pip-install-n23692y_/rapidyaml_76260b282025438ea3e1f96d2a36d871/api/python/build/temp.linux-x86_64-3.7_ryml.ryml --target install
  
  Traceback (most recent call last):
    File "/home/charm/FPGA/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 280, in <module>
      main()
    File "/home/charm/FPGA/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 263, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/home/charm/FPGA/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 205, in build_wheel
      metadata_directory)
    File "/tmp/pip-build-env-nt8a7swt/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 217, in build_wheel
      wheel_directory, config_settings)
    File "/tmp/pip-build-env-nt8a7swt/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 202, in _build_with_temp_dir
      self.run_setup()
    File "/tmp/pip-build-env-nt8a7swt/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 254, in run_setup
      self).run_setup(setup_script=setup_script)
    File "/tmp/pip-build-env-nt8a7swt/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 145, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 31, in <module>
      license='MIT',
    File "/tmp/pip-build-env-nt8a7swt/overlay/lib/python3.7/site-packages/setuptools/__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "/home/charm/FPGA/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/lib/python3.7/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/home/charm/FPGA/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/lib/python3.7/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/home/charm/FPGA/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/tmp/pip-build-env-nt8a7swt/overlay/lib/python3.7/site-packages/wheel/bdist_wheel.py", line 299, in run
      self.run_command('build')
    File "/home/charm/FPGA/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/lib/python3.7/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/home/charm/FPGA/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/home/charm/FPGA/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/lib/python3.7/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/home/charm/FPGA/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/lib/python3.7/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/home/charm/FPGA/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/tmp/pip-build-env-nt8a7swt/overlay/lib/python3.7/site-packages/cmake_build_extension/build_extension.py", line 66, in run
      self.build_extension(ext)
    File "/tmp/pip-build-env-nt8a7swt/overlay/lib/python3.7/site-packages/cmake_build_extension/build_extension.py", line 171, in build_extension
      subprocess.check_call(configure_command)
    File "/home/charm/FPGA/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/lib/python3.7/subprocess.py", line 363, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['cmake', '-S', '/tmp/pip-install-n23692y_/rapidyaml_76260b282025438ea3e1f96d2a36d871/api/python/../..', '-B', '/tmp/pip-install-n23692y_/rapidyaml_76260b282025438ea3e1f96d2a36d871/api/python/build/temp.linux-x86_64-3.7_ryml.ryml', '-GNinja', '-DCMAKE_BUILD_TYPE=Release', '-DCMAKE_INSTALL_PREFIX:PATH=/tmp/pip-install-n23692y_/rapidyaml_76260b282025438ea3e1f96d2a36d871/api/python/build/lib.linux-x86_64-3.7/ryml', '-DRYML_BUILD_API:BOOL=ON']' returned non-zero exit status 1.
  ----------------------------------------
  ERROR: Failed building wheel for rapidyaml
ERROR: Could not build wheels for rapidyaml which use PEP 517 and cannot be installed directly

failed

CondaEnvException: Pip failed

make: *** [third_party/make-env/conda.mk:128: /home/charm/FPGA/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/python] Error 1
```

**Comment by litghost** [comment]
The error is here:
```
  -- ryml: packing the project
  -- ryml: enabling API
  CMake Error at /home/charm/FPGA/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/share/cmake-3.19/Modules/FindPackageHandleStandardArgs.cmake:218 (message):
    Could NOT find SWIG (missing: SWIG_EXECUTABLE SWIG_DIR)
```

E.g. swig is not installed.

**Comment by mgerlach-phys** [comment]
Oh yes, thanks!
