### ISSUE TITLE
Fix multi process make support

### ISSUE THREAD

**Issue by acomodi** [SymbiFlow/symbiflow-arch-defs#337]
When building the xc7 tests, the compilation fails because of a bad JSON formatting.

```
$ make -j`nproc` buttons_basys3_bin
...
[ 75%] Generating pin_assignments.json
2019-01-24 13:05:12.906626 Reading channel data
[ 75%] Built target file__home_build_symbiflow-arch-defs_xc7_archs_artix7_channels.json
Traceback (most recent call last):
  File "/home/build/symbiflow-arch-defs/xc7/utils/prjxray_assign_tile_pin_direction.py", line 290, in <module>
    main()
  File "/home/build/symbiflow-arch-defs/xc7/utils/prjxray_assign_tile_pin_direction.py", line 48, in main
    channels = json.load(f)
  File "/home/build/symbiflow-arch-defs/build/env/conda/lib/python3.7/site-packages/simplejson/__init__.py", line 461, in load
    use_decimal=use_decimal, **kw)
  File "/home/build/symbiflow-arch-defs/build/env/conda/lib/python3.7/site-packages/simplejson/__init__.py", line 518, in loads
    return _default_decoder.decode(s)
  File "/home/build/symbiflow-arch-defs/build/env/conda/lib/python3.7/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/home/build/symbiflow-arch-defs/build/env/conda/lib/python3.7/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Invalid control character '\n' at: line 39095170 column 24 (char 680797465)
xc7/archs/artix7/CMakeFiles/file__home_build_symbiflow-arch-defs_xc7_archs_artix7_pin_assignments.json.dir/build.make:240: recipe for target 'xc7/archs/artix7/pin_assignments.json' failed
make[3]: *** [xc7/archs/artix7/pin_assignments.json] Error 1
CMakeFiles/Makefile2:30600: recipe for target 'xc7/archs/artix7/CMakeFiles/file__home_build_symbiflow-arch-defs_xc7_archs_artix7_pin_assignments.json.dir/all' failed
make[2]: *** [xc7/archs/artix7/CMakeFiles/file__home_build_symbiflow-arch-defs_xc7_archs_artix7_pin_assignments.json.dir/all] Error 2
CMakeFiles/Makefile2:34896: recipe for target 'xc7/tests/buttons/CMakeFiles/buttons_basys3_bin.dir/rule' failed
make[1]: *** [xc7/tests/buttons/CMakeFiles/buttons_basys3_bin.dir/rule] Error 2
Makefile:10859: recipe for target 'buttons_basys3_bin' failed
make: *** [buttons_basys3_bin] Error 2

```

This behavior is non-deterministic and it is probably due to the parallel compilation. By doing `make clean` or deleting the `channel.json` file and re-building (even a few times) the pin_assignment step successfully completes.

**Comment by litghost** [comment]
I assume this occurs on https://github.com/SymbiFlow/symbiflow-arch-defs/pull/333 ?  Can you replicate this issue occurs on master as well?  If not, it may represent a regression in #333

**Comment by acomodi** [comment]
I am going to check this behavior on the master then and see if the problem still occurs

**Comment by acomodi** [comment]
I have run the `buttons` test on the master and replicated the same kind of error:

```
$ make -j`nproc` buttons_bin

2019-01-28 16:41:30.058949 Reading channel data
Traceback (most recent call last):
  File "/home/build/symbiflow-arch-defs/xc7/utils/prjxray_assign_tile_pin_direction.py", line 290, in <module>
    main()
  File "/home/build/symbiflow-arch-defs/xc7/utils/prjxray_assign_tile_pin_direction.py", line 48, in main
    channels = json.load(f)
  File "/home/build/symbiflow-arch-defs/build/env/conda/lib/python3.7/site-packages/simplejson/__init__.py", line 461, in load
    use_decimal=use_decimal, **kw)
  File "/home/build/symbiflow-arch-defs/build/env/conda/lib/python3.7/site-packages/simplejson/__init__.py", line 518, in loads
    return _default_decoder.decode(s)
  File "/home/build/symbiflow-arch-defs/build/env/conda/lib/python3.7/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/home/build/symbiflow-arch-defs/build/env/conda/lib/python3.7/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Invalid control character '\n' at: line 47669279 column 21 (char 827352195)
xc7/CMakeFiles/file__home_build_symbiflow-arch-defs_xc7_pin_assignments.json.dir/build.make:240: recipe for target 'xc7/pin_assignments.json' failed
make[3]: *** [xc7/pin_assignments.json] Error 1
CMakeFiles/Makefile2:6421: recipe for target 'xc7/CMakeFiles/file__home_build_symbiflow-arch-defs_xc7_pin_assignments.json.dir/all' failed
make[2]: *** [xc7/CMakeFiles/file__home_build_symbiflow-arch-defs_xc7_pin_assignments.json.dir/all] Error 2
CMakeFiles/Makefile2:32620: recipe for target 'xc7/tests/buttons/CMakeFiles/buttons_bin.dir/rule' failed
make[1]: *** [xc7/tests/buttons/CMakeFiles/buttons_bin.dir/rule] Error 2
Makefile:10378: recipe for target 'buttons_bin' failed
make: *** [buttons_bin] Error 2
```

By cleaning and re-building it went through the pin_assignment step

**Comment by litghost** [comment]
There is also a bug in the conda support with multi processes.  I'll submit a PR to fix both.
