### ISSUE TITLE
make on checkout fails

### ISSUE THREAD

**Issue by mithro** [SymbiFlow/symbiflow-arch-defs#448]
```
make[3]: *** No rule to make target '../third_party/prjxray-db/zynq7/harness/zybo/swbut/design.json', needed by 'xc7/archs/zynq7/devices/xc7z010-roi-virt/arch.xml'.  Stop.
make[3]: Leaving directory '/usr/local/google/home/tansell/github/SymbiFlow/symbiflow-arch-defs-docs/build'
CMakeFiles/Makefile2:34373: recipe for target 'xc7/archs/zynq7/devices/xc7z010-roi-virt/CMakeFiles/file_xc7_archs_zynq7_devices_xc7z010-roi-virt_synth_tiles.json.dir/all' failed
make[2]: *** [xc7/archs/zynq7/devices/xc7z010-roi-virt/CMakeFiles/file_xc7_archs_zynq7_devices_xc7z010-roi-virt_synth_tiles.json.dir/all] Error 2
make[2]: Leaving directory '/usr/local/google/home/tansell/github/SymbiFlow/symbiflow-arch-defs-docs/build'
Makefile:140: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/usr/local/google/home/tansell/github/SymbiFlow/symbiflow-arch-defs-docs/build'
Makefile:4: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by mithro** [comment]
@litghost Can we remove the zybo build from the default 'all' target? Or should make some other target be the default?

**Comment by mithro** [comment]
Harness was merged with the merge of https://github.com/SymbiFlow/symbiflow-arch-defs/pull/459

Now the failure is;
```
[  0%] Generating simplejson.pip
Requirement already satisfied: simplejson in /usr/local/google/home/tansell/github/SymbiFlow/symbiflow-arch-defs/build/env/conda/lib/python3.7/site-packages (3.16.0)
make[3]: Leaving directory '/usr/local/google/home/tansell/github/SymbiFlow/symbiflow-arch-defs/build'
[  0%] Built target simplejson
make[3]: Entering directory '/usr/local/google/home/tansell/github/SymbiFlow/symbiflow-arch-defs/build'
Scanning dependencies of target file_xc7_archs_zynq7_channels.db
make[3]: Leaving directory '/usr/local/google/home/tansell/github/SymbiFlow/symbiflow-arch-defs/build'
make[3]: Entering directory '/usr/local/google/home/tansell/github/SymbiFlow/symbiflow-arch-defs/build'
[  0%] Generating channels.db
2019-03-13 17:42:57.685445: About to load database
Traceback (most recent call last):
  File "/usr/local/google/home/tansell/github/SymbiFlow/symbiflow-arch-defs/xc7/utils/prjxray_form_channels.py", line 718, in <module>
    main()
  File "/usr/local/google/home/tansell/github/SymbiFlow/symbiflow-arch-defs/xc7/utils/prjxray_form_channels.py", line 706, in main
    import_grid(db, grid, conn)
  File "/usr/local/google/home/tansell/github/SymbiFlow/symbiflow-arch-defs/xc7/utils/prjxray_form_channels.py", line 161, in import_grid
    import_tile_type(db, c, tile_types, site_types, gridinfo.tile_type)
  File "/usr/local/google/home/tansell/github/SymbiFlow/symbiflow-arch-defs/xc7/utils/prjxray_form_channels.py", line 97, in import_tile_type
    import_site_type(db, c, site_types, site.type)
  File "/usr/local/google/home/tansell/github/SymbiFlow/symbiflow-arch-defs/xc7/utils/prjxray_form_channels.py", line 48, in import_site_type
    site_type = db.get_site_type(site_type_name)
  File "/usr/local/google/home/tansell/github/SymbiFlow/symbiflow-arch-defs/third_party/prjxray/prjxray/db.py", line 142, in get_site_type
    return site_type.SiteType(site_type_data)
  File "/usr/local/google/home/tansell/github/SymbiFlow/symbiflow-arch-defs/third_party/prjxray/prjxray/site_type.py", line 22, in __init__
    direction=SitePinDirection(site_pin_info['direction']),
  File "/usr/local/google/home/tansell/github/SymbiFlow/symbiflow-arch-defs/build/env/conda/lib/python3.7/enum.py", line 309, in __call__
    return cls.__new__(cls, value)
  File "/usr/local/google/home/tansell/github/SymbiFlow/symbiflow-arch-defs/build/env/conda/lib/python3.7/enum.py", line 543, in __new__
    return cls._missing_(value)
  File "/usr/local/google/home/tansell/github/SymbiFlow/symbiflow-arch-defs/build/env/conda/lib/python3.7/enum.py", line 556, in _missing_
    raise ValueError("%r is not a valid %s" % (value, cls.__name__))
ValueError: 'INOUT' is not a valid SitePinDirection
xc7/archs/zynq7/CMakeFiles/file_xc7_archs_zynq7_channels.db.dir/build.make:218: recipe for target 'xc7/archs/zynq7/channels.db' failed
make[3]: *** [xc7/archs/zynq7/channels.db] Error 1
make[3]: *** Deleting file 'xc7/archs/zynq7/channels.db'
make[3]: Leaving directory '/usr/local/google/home/tansell/github/SymbiFlow/symbiflow-arch-defs/build'
CMakeFiles/Makefile2:32901: recipe for target 'xc7/archs/zynq7/CMakeFiles/file_xc7_archs_zynq7_channels.db.dir/all' failed
make[2]: *** [xc7/archs/zynq7/CMakeFiles/file_xc7_archs_zynq7_channels.db.dir/all] Error 2
make[2]: Leaving directory '/usr/local/google/home/tansell/github/SymbiFlow/symbiflow-arch-defs/build'
Makefile:140: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/usr/local/google/home/tansell/github/SymbiFlow/symbiflow-arch-defs/build'
Makefile:4: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by mithro** [comment]
With the following patch, it gets to doing vpr for the zynq,
```patch
diff --git a/third_party/prjxray b/third_party/prjxray
--- a/third_party/prjxray
+++ b/third_party/prjxray
@@ -1 +1 @@
-Subproject commit 45a8af8d71c285e7115112c564e5d46b6c81dd97
+Subproject commit 45a8af8d71c285e7115112c564e5d46b6c81dd97-dirty
diff --git a/xc7/utils/prjxray_create_edges.py b/xc7/utils/prjxray_create_edges.py
index 5fbb798..e5d6222 100644
--- a/xc7/utils/prjxray_create_edges.py
+++ b/xc7/utils/prjxray_create_edges.py
@@ -77,6 +77,9 @@ WHERE
         node_type = NodeType.IPIN
     elif pin_direction == SitePinDirection.OUT:
         node_type = NodeType.OPIN
+    # FIXME: Support INOUT pins
+    elif pin_direction == SitePinDirection.INOUT:
+        node_type = NodeType.OPIN
     else:
         assert False, pin_direction
 
```

However, the place and route of wire.eblif fails with;
```
/tmp/really-really-really-really-really-really-really-really-really-really-really-really-really-long-path/conda/conda-bld/vtr_1551905723204/work/vpr/src/route/rr_graph2.cpp:855 is_cblock: Assertion 'ofs < length' failed.
```

```
RoutingArch.switch_block_type: WILTON
RoutingArch.Fs: 3

# Packing
Begin packing '/usr/local/google/home/tansell/github/SymbiFlow/symbiflow-arch-defs/common/wire.eblif'.

After removing unused inputs...
        total blocks: 3, total nets: 2, total inputs: 1, total outputs: 1
Begin prepacking.
Finish prepacking.
Using inter-cluster delay: 6.74304e-10
Packing with pin utilization targets: BLK_TI-INT_R:1,1 BLK_TI-INT_L:1,1 BLK_TI-CLBLL_R:0.8,1 BLK_TI-CLBLL_L:1,1 BLK_TI-CLBLM_R:1,1 BLK_TI-CLBLM_L:1,1 BLK_TI-BRAM_L:1,1 BLK_SY-INPAD:1,1 BLK_SY-OUTPAD:1,1
Not enough resources expand FPGA size to (129 x 106)
Complex block 0: do, type: BLK_TI-CLBLL_R .
Complex block 1: out:do, type: BLK_SY-OUTPAD .
Complex block 2: di, type: BLK_SY-INPAD ./tmp/really-really-really-really-really-really-really-really-really-really-really-really-really-long-path/conda/conda-bld/vtr_1551905723204/work/vpr/src/route/rr_graph2.cpp:855 is_cblock: Assertion 'ofs < length' failed.

        EMPTY: # blocks: 0, average # input + clock pins used: 0, average # output pins used: 0
        BLK_TI-INT_R: # blocks: 0, average # input + clock pins used: 0, average # output pins used: 0
        BLK_TI-INT_L: # blocks: 0, average # input + clock pins used: 0, average # output pins used: 0
        BLK_TI-CLBLL_R: # blocks: 1, average # input + clock pins used: 1, average # output pins used: 1
        BLK_TI-CLBLL_L: # blocks: 0, average # input + clock pins used: 0, average # output pins used: 0
        BLK_TI-CLBLM_R: # blocks: 0, average # input + clock pins used: 0, average # output pins used: 0
        BLK_TI-CLBLM_L: # blocks: 0, average # input + clock pins used: 0, average # output pins used: 0
        BLK_TI-BRAM_L: # blocks: 0, average # input + clock pins used: 0, average # output pins used: 0
        BLK_SY-INPAD: # blocks: 1, average # input + clock pins used: 0, average # output pins used: 1
        BLK_SY-OUTPAD: # blocks: 1, average # input + clock pins used: 1, average # output pins used: 0
Absorbed logical nets 0 out of 2 nets, 2 nets not absorbed.
FPGA sized to 129 x 106 (xc7z010-test)
Device Utilization: 0.00 (target 1.00)
        Block Utilization: 0.02 Type: BLK_TI-CLBLL_R
        Block Utilization: 0.00 Type: BLK_TI-CLBLL_L
        Block Utilization: 0.00 Type: BLK_TI-CLBLM_R
        Block Utilization: 0.00 Type: BLK_TI-CLBLM_L
        Block Utilization: 0.20 Type: BLK_SY-INPAD
        Block Utilization: 0.17 Type: BLK_SY-OUTPAD


Netlist conversion complete.

# Packing took 0.08 seconds (max_rss 39.3 MiB, delta_rss +20.0 MiB)
# Load Packing
Begin loading packed FPGA netlist file.
Netlist generated from file 'wire.net'.
Finished loading packed FPGA netlist file (took 0.00388 seconds).
# Load Packing took 0.01 seconds (max_rss 39.3 MiB, delta_rss +0.0 MiB)
Warning 616: Logic block #2 (di) has only 1 input pin 'di.inpad' -- the whole block is hanging logic that should be swept.

Netlist num_nets: 2
Netlist num_blocks: 3
Netlist EMPTY blocks: 0.
Netlist BLK_TI-INT_R blocks: 0.
Netlist BLK_TI-INT_L blocks: 0.
Netlist BLK_TI-CLBLL_R blocks: 1.
Netlist BLK_TI-CLBLL_L blocks: 0.
Netlist BLK_TI-CLBLM_R blocks: 0.
Netlist BLK_TI-CLBLM_L blocks: 0.
Netlist BLK_TI-BRAM_L blocks: 0.
Netlist BLK_SY-INPAD blocks: 1.
Netlist BLK_SY-OUTPAD blocks: 1.
Netlist inputs pins: 1
Netlist output pins: 1

# Create Device
## Build Device Grid
FPGA sized to 129 x 106: 13674 grid tiles (xc7z010-test)

Resource usage...
        Netlist      0  blocks of type: EMPTY
        Architecture 0  blocks of type: EMPTY
        Netlist      0  blocks of type: BLK_TI-INT_R
        Architecture 350        blocks of type: BLK_TI-INT_R
        Netlist      0  blocks of type: BLK_TI-INT_L
        Architecture 350        blocks of type: BLK_TI-INT_L
        Netlist      1  blocks of type: BLK_TI-CLBLL_R
        Architecture 50 blocks of type: BLK_TI-CLBLL_R
        Netlist      0  blocks of type: BLK_TI-CLBLL_L
        Architecture 150        blocks of type: BLK_TI-CLBLL_L
        Netlist      0  blocks of type: BLK_TI-CLBLM_R
        Architecture 250        blocks of type: BLK_TI-CLBLM_R
        Netlist      0  blocks of type: BLK_TI-CLBLM_L
        Architecture 100        blocks of type: BLK_TI-CLBLM_L
        Netlist      0  blocks of type: BLK_TI-BRAM_L
        Architecture 10 blocks of type: BLK_TI-BRAM_L
        Netlist      1  blocks of type: BLK_SY-INPAD
        Architecture 5  blocks of type: BLK_SY-INPAD
        Netlist      1  blocks of type: BLK_SY-OUTPAD
        Architecture 6  blocks of type: BLK_SY-OUTPAD

Device Utilization: 0.00 (target 1.00)
        Block Utilization: 0.00 Type: EMPTY
        Block Utilization: 0.00 Type: BLK_TI-INT_R
        Block Utilization: 0.00 Type: BLK_TI-INT_L
        Block Utilization: 0.02 Type: BLK_TI-CLBLL_R
        Block Utilization: 0.00 Type: BLK_TI-CLBLL_L
        Block Utilization: 0.00 Type: BLK_TI-CLBLM_R
        Block Utilization: 0.00 Type: BLK_TI-CLBLM_L
        Block Utilization: 0.00 Type: BLK_TI-BRAM_L
        Block Utilization: 0.20 Type: BLK_SY-INPAD
        Block Utilization: 0.17 Type: BLK_SY-OUTPAD

## Build Device Grid took 0.02 seconds (max_rss 39.3 MiB, delta_rss +0.0 MiB)
## Build routing resource graph
xc7/archs/zynq7/devices/CMakeFiles/file_xc7_archs_zynq7_devices_rr_graph_xc7z010_test.rr_graph.real.xml.dir/build.make:71: recipe for target 'xc7/archs/zynq7/devices/rr_graph_xc7z010_test.rr_graph.virt.xml' failed
make[3]: *** [xc7/archs/zynq7/devices/rr_graph_xc7z010_test.rr_graph.virt.xml] Error 134
make[3]: Leaving directory '/usr/local/google/home/tansell/github/SymbiFlow/symbiflow-arch-defs/build'
CMakeFiles/Makefile2:34137: recipe for target 'xc7/archs/zynq7/devices/CMakeFiles/file_xc7_archs_zynq7_devices_rr_graph_xc7z010_test.rr_graph.real.xml.dir/all' failed
make[2]: *** [xc7/archs/zynq7/devices/CMakeFiles/file_xc7_archs_zynq7_devices_rr_graph_xc7z010_test.rr_graph.real.xml.dir/all] Error 2
make[2]: Leaving directory '/usr/local/google/home/tansell/github/SymbiFlow/symbiflow-arch-defs/build'
Makefile:140: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/usr/local/google/home/tansell/github/SymbiFlow/symbiflow-arch-defs/build'
Makefile:4: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by mithro** [comment]
https://github.com/SymbiFlow/prjxray/pull/725
