### ISSUE TITLE
sqlite errors when doing parallel build

### ISSUE THREAD

**Issue by mithro** [SymbiFlow/symbiflow-arch-defs#466]
```
Scanning dependencies of target file_xc7_primitives_common_slice_common_lut_and_f78mux.pb_type.xml     
make[3]: Leaving directory '/usr/local/google/home/tansell/github/SymbiFlow/symbiflow-arch-defs/build' 
Traceback (most recent call last):                                                    
  File "/usr/local/google/home/tansell/github/SymbiFlow/symbiflow-arch-defs/xc7/utils/prjxray_form_channels.py", line 718, in <module>
    main()                                                                                            
  File "/usr/local/google/home/tansell/github/SymbiFlow/symbiflow-arch-defs/xc7/utils/prjxray_form_channels.py", line 701, in main
    create_tables(conn)                                                  
  File "/usr/local/google/home/tansell/github/SymbiFlow/symbiflow-arch-defs/utils/lib/connection_database.py", line 67, in create_tables
    );""")                                                                                                                   
sqlite3.OperationalError: attempt to write a readonly database         
| Traceback (most recent call last):                                
  File "/usr/local/google/home/tansell/github/SymbiFlow/symbiflow-arch-defs/xc7/utils/prjxray_form_channels.py", line 718, in <module>
    main()                                                            
  File "/usr/local/google/home/tansell/github/SymbiFlow/symbiflow-arch-defs/xc7/utils/prjxray_form_channels.py", line 701, in main          
    create_tables(conn)                                                                                                                     
  File "/usr/local/google/home/tansell/github/SymbiFlow/symbiflow-arch-defs/utils/lib/connection_database.py", line 67, in create_tables    
    );""")                                                                                                                                  
sqlite3.OperationalError: attempt to write a readonly database                                                                               make[3]: Entering directory '/usr/local/google/home/tansell/github/SymbiFlow/symbiflow-arch-defs/build'
- xc7/archs/zynq7/CMakeFiles/file_xc7_archs_zynq7_pin_assignments.json.dir/build.make:381: recipe for target 'xc7/archs/zynq7/channels.db' fa
iled                                                                                                                                         make[3]: *** [xc7/archs/zynq7/channels.db] Error 1                                                     
make[3]: *** Deleting file 'xc7/archs/zynq7/channels.db'                                                                                    
make[3]: Leaving directory '/usr/local/google/home/tansell/github/SymbiFlow/symbiflow-arch-defs/build'
CMakeFiles/Makefile2:32894: recipe for target 'xc7/archs/zynq7/CMakeFiles/file_xc7_archs_zynq7_pin_assignments.json.dir/all' failed
make[2]: *** [xc7/archs/zynq7/CMakeFiles/file_xc7_archs_zynq7_pin_assignments.json.dir/all] Error 2                 
make[2]: *** Waiting for unfinished jobs....                                                           
Traceback (most recent call last):
  File "/usr/local/google/home/tansell/github/SymbiFlow/symbiflow-arch-defs/xc7/utils/prjxray_form_channels.py", line 718, in <module>
    main()                                                                         
  File "/usr/local/google/home/tansell/github/SymbiFlow/symbiflow-arch-defs/xc7/utils/prjxray_form_channels.py", line 701, in main
    create_tables(conn)                                                                                                      
  File "/usr/local/google/home/tansell/github/SymbiFlow/symbiflow-arch-defs/utils/lib/connection_database.py", line 67, in create_tables
    );""")                                                                         
sqlite3.OperationalError: disk I/O error                                                              
xc7/archs/artix7/CMakeFiles/file_xc7_archs_artix7_pin_assignments.json.dir/build.make:435: recipe for target 'xc7/archs/artix7/channels.db' f
ailed                                                                              
make[3]: *** [xc7/archs/artix7/channels.db] Error 1
make[3]: *** Deleting file 'xc7/archs/artix7/channels.db'                                                                                   
make[3]: Leaving directory '/usr/local/google/home/tansell/github/SymbiFlow/symbiflow-arch-defs/build'                           
CMakeFiles/Makefile2:30907: recipe for target 'xc7/archs/artix7/CMakeFiles/file_xc7_archs_artix7_pin_assignments.json.dir/all' failed
make[2]: *** [xc7/archs/artix7/CMakeFiles/file_xc7_archs_artix7_pin_assignments.json.dir/all] Error 2                
- Traceback (most recent call last):                                                                  
  File "/usr/local/google/home/tansell/github/SymbiFlow/symbiflow-arch-defs/xc7/utils/prjxray_form_channels.py", line 718, in <module>
    main()                                                                            
  File "/usr/local/google/home/tansell/github/SymbiFlow/symbiflow-arch-defs/xc7/utils/prjxray_form_channels.py", line 701, in main
    create_tables(conn)           
  File "/usr/local/google/home/tansell/github/SymbiFlow/symbiflow-arch-defs/utils/lib/connection_database.py", line 60, in create_tables
    );""")                           
sqlite3.OperationalError: disk I/O error    
```

**Comment by litghost** [comment]
Duplicate: https://github.com/SymbiFlow/symbiflow-arch-defs/issues/337
